spring:
  application:
    name: BankingManagementSystem

  datasource:
    url:  ${DEV_DB_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: BankingPool

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,caches